---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: emberstack
  namespace: flux-system
spec:
  url: https://emberstack.github.io/helm-charts
  interval: 10m
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: reflector
  namespace: reflector
spec:
  chart:
    spec:
      chart: reflector
      version: "7.1.221"
      sourceRef:
        kind: HelmRepository
        name: emberstack
        namespace: flux-system
  interval: 5m
