apiVersion: apps/v1
kind: Deployment
metadata:
  name: cert-manager-cainjector
spec:
  template:
    spec:
      containers:
        - name: manager
          image: 043309336908.dkr.ecr.us-west-1.amazonaws.com/ce-addon-images/jetstack-cert-manager-cainjector:v1.12.0
