apiVersion: apps/v1
kind: Deployment
metadata:
  name: dns-external-dns
spec:
  template:
    spec:
      containers:
        - name: manager
          image: 043309336908.dkr.ecr.us-west-1.amazonaws.com/ce-addon-images/external-dns-external-dns:v0.13.6
