apiVersion: apps/v1
kind: Deployment
metadata:
  name: keda-metrics-apiserver
spec:
  template:
    spec:
      containers:
        - name: manager
          image: 043309336908.dkr.ecr.us-west-2.amazonaws.com/ce-addon-images/kedacore-keda-metrics-apiserver:2.14.0
