apiVersion: apps/v1
kind: Deployment
metadata:
  name: pilot
spec:
  template:
    spec:
      containers:
        - name: manager
          image: 043309336908.dkr.ecr.us-west-1.amazonaws.com/ce-addon-images/istio-pilot:1.22.0
