apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: reflector
  namespace: flux-system
spec:
  interval: 5m
  releaseName: reflector
  targetNamespace: kraken-system
  chartRef:
    kind: OCIRepository
    name: ce-reflector-chart
    namespace: flux-system

