apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: reflector
  namespace: flux-system
spec:
  interval: 10m
  url: oci://043309336908.dkr.ecr.us-west-1.amazonaws.com/ce-addon-charts/reflector
  ref:
    tag: 9.1.7
  secretRef:
    name: ce-ecr-auth