---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: emberstack
  namespace: flux-system
spec:
  url: https://emberstack.github.io/helm-charts
  interval: 10m
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: reflector
  namespace: flux-system
spec:
  targetNamespace: shared-system
  chart:
    spec:
      chart: reflector
      version: "9.1.7"
      sourceRef:
        kind: HelmRepository
        name: emberstack
        namespace: flux-system
  interval: 5m

  postRenderers:
    - kustomize:
        patches:
          - patch: |
              apiVersion: apps/v1
              kind: Deployment
              metadata:
                name: shared-system-reflector
              spec:
                template:
                  spec:
                    containers:
                      - name: reflector
                        image: 043309336908.dkr.ecr.us-west-2.amazonaws.com/ce-addon-images/emberstack-kubernetes-reflector:9.1.7
