apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: reflector
  namespace: flux-system
spec:
  interval: 5m
  targetNamespace: kraken-system
  chart:
    spec:
      #chart: oci://043309336908.dkr.ecr.us-west-2.amazonaws.com/ce-helm-charts/reflector
      #version: "9.1.7"
      chartRef:
        kind: OCIRepository
        name: ce-reflector-chart
        namespace: flux-system

  postRenderers:
    - kustomize:
        patches:
          - patch: |
              apiVersion: apps/v1
              kind: Deployment
              metadata:
                name: kraken-system-reflector
                namespace: kraken-system
              spec:
                template:
                  spec:
                    containers:
                      - name: reflector
                        image: 043309336908.dkr.ecr.us-west-2.amazonaws.com/ce-addon-images/emberstack-kubernetes-reflector:9.1.7