apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: kraken-system
spec:
  targetNamespace: kraken-system
  chartRef:
    kind: OCIRepository
    name: cert-manager
    namespace: flux-system
  interval: 5m
  releaseName: cert-manager
  values:
    installCRDs: true
  postRenderers:
    - kustomize:
        patches:
          - patch: |
              apiVersion: apps/v1
              kind: Deployment
              metadata:
                name: cert-manager
              spec:
                template:
                  spec:
                    containers:
                      - name: cert-manager-controller
                        image: 043309336908.dkr.ecr.us-west-1.amazonaws.com/ce-addon-images/jetstack-cert-manager-controller:v1.12.0
          - patch: |
              apiVersion: apps/v1
              kind: Deployment
              metadata:
                name: cert-manager-webhook
              spec:
                template:
                  spec:
                    containers:
                      - name: cert-manager-webhook
                        image: 043309336908.dkr.ecr.us-west-1.amazonaws.com/ce-addon-images/jetstack-cert-manager-webhook:v1.12.0
          - patch: |
              apiVersion: apps/v1
              kind: Deployment
              metadata:
                name: cert-manager-cainjector
              spec:
                template:
                  spec:
                    containers:
                      - name: cert-manager-cainjector
                        image: 043309336908.dkr.ecr.us-west-1.amazonaws.com/ce-addon-images/cert-manager-cainjector:v1.12.0