apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gatekeeper
  namespace: flux-system
spec:
  install:
    createNamespace: true
  targetNamespace: gatekeeper-system
  chart:
    spec:
      chart: gatekeeper
      version: "3.14.0"
      sourceRef:
        kind: HelmRepository
        name: gatekeeper
        namespace: flux-system
  interval: 5m