apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: gatekeeper
  namespace: flux-system
spec:
  interval: 10m
  url: oci://043309336908.dkr.ecr.us-west-1.amazonaws.com/ce-addon-charts/gatekeeper
  ref:
    tag: 3.14.0
  secretRef:
    name: ce-ecr-auth