apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gatekeeper
  namespace: gatekeeper-system
spec:
  install:
    createNamespace: true
  targetNamespace: gatekeeper-system
  chartRef:
    kind: OCIRepository
    name: gatekeeper
    namespace: flux-system
  interval: 5m
  releaseName: gatekeeper
  # postRenderers:
  #   - kustomize:
  #       patches:
  #         - patch: |
  #             apiVersion: apps/v1
  #             kind: Deployment
  #             metadata:
  #               name: gatekeeper
  #             spec:
  #               template:
  #                 spec:
  #                   containers:
  #                     - name: manager
  #                       image: 043309336908.dkr.ecr.us-west-1.amazonaws.com/ce-addon-images/gatekeeper:v3.14.0