apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: keda
  namespace: kraken-system
spec:
  targetNamespace: kraken-system
  chartRef:
    kind: OCIRepository
    name: keda
    namespace: flux-system
  interval: 5m
  releaseName: keda

  postRenderers:
    - kustomize:
        patches:
          - patch: |
              apiVersion: apps/v1
              kind: Deployment
              metadata:
                name: keda-operator
                namespace: kraken-system
              spec:
                template:
                  spec:
                    containers:
                      - name: keda-operator
                        image: 043309336908.dkr.ecr.us-west-1.amazonaws.com/ce-addon-images/kedacore-keda:2.14.0
          - patch: |
              apiVersion: apps/v1
              kind: Deployment
              metadata:
                name: keda-admission-webhooks
                namespace: kraken-system
              spec:
                template:
                  spec:
                    containers:
                      - name: keda-admission-webhooks
                        image: 043309336908.dkr.ecr.us-west-1.amazonaws.com/ce-addon-images/kedacore-keda-admission-webhooks:2.14.0
          - patch: |
              apiVersion: apps/v1
              kind: Deployment
              metadata:
                name: keda-operator-metrics-apiserver
                namespace: kraken-system
              spec:
                template:
                  spec:
                    containers:
                      - name: keda-operator-metrics-apiserver
                        image: 043309336908.dkr.ecr.us-west-1.amazonaws.com/ce-addon-images/kedacore-keda-metrics-apiserver:2.14.0