---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: ce-kedacore-chart
  namespace: flux-system
spec:
  interval: 10m
  url: oci://043309336908.dkr.ecr.us-west-1.amazonaws.com/ce-addon-charts/keda
  ref:
    tag: 2.14.2
  secretRef:
    name: ce-ecr-auth