apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-dns
  namespace: kraken-system
spec:
  targetNamespace: kraken-system
  chartRef:
    kind: OCIRepository
    name: external-dns
    namespace: flux-system
  interval: 5m
  releaseName: external-dns
  values:
    provider: aws
    policy: upsert-only
    registry: txt
    txtOwnerId: gardener
    domainFilters:
      - yourdomain.com
    serviceMonitor:
      enabled: false
  postRenderers:
    - kustomize:
        patches:
          - patch: |
              apiVersion: apps/v1
              kind: Deployment
              metadata:
                name: dns-external-dns
              spec:
                template:
                  spec:
                    containers:
                      - name: manager
                        image: 043309336908.dkr.ecr.us-west-1.amazonaws.com/ce-addon-images/external-dns-external-dns:v0.13.6
