---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: external-dns
  namespace: flux-system
spec:
  url: https://kubernetes-sigs.github.io/external-dns/
  interval: 10m
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-dns
  namespace: flux-system
spec:
  targetNamespace: shared-system
  chart:
    spec:
      chart: external-dns
      version: "1.13.1"
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: flux-system
  interval: 5m
  values:
    provider: aws
    policy: upsert-only
    registry: txt
    txtOwnerId: gardener
    domainFilters:
      - yourdomain.com
    serviceMonitor:
      enabled: false