---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: kedacore
  namespace: flux-system
spec:
  url: https://kedacore.github.io/charts
  interval: 10m
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: keda
  namespace: flux-system
spec:
  install:
    createNamespace: true
  targetNamespace: kraken-system
  chart:
    spec:
      chart: keda
      version: "2.14.2"
      sourceRef:
        kind: HelmRepository
        name: kedacore
        namespace: flux-system
  interval: 5m
