# HelmRepository: This must remain in the flux-system namespace
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: jetstack
  namespace: flux-system
spec:
  url: https://charts.jetstack.io
  interval: 10m
---
# HelmRelease: This installs cert-manager into kraken-system
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: kraken-system
spec:
  install:
    createNamespace: true
  targetNamespace: kraken-system
  interval: 1h
  chart:
    spec:
      chart: cert-manager
      version: v1.12.0
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: flux-system
  values:
    installCRDs: true