apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istio-base
  namespace: flux-system
spec:
  install:
    createNamespace: true
  targetNamespace: istio-system
  chart:
    spec:
      chart: base
      version: "1.22.0"
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: flux-system
  interval: 5m
  releaseName: base
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istiod
  namespace: flux-system
spec:
  install:
    createNamespace: true
  targetNamespace: istio-system
  chart:
    spec:
      chart: istiod
      version: "1.22.0"
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: flux-system
  interval: 5m
  releaseName: istiod
  dependsOn:
    - name: istio-base
  values:
    meshConfig:
      accessLogFile: "/dev/stdout"
    pilot:
      autoscaleEnabled: true
  postRenderers:
    - kustomize:
        patches:
          - patch: |

