apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istio-base
  namespace: istio-system
spec:
  install:
    createNamespace: true
  targetNamespace: istio-system
  chartRef:
    kind: OCIRepository
    name: istiod
    namespace: flux-system
  interval: 5m
  releaseName: base
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istiod
  namespace: istio-system
spec:
  install:
    createNamespace: true
  targetNamespace: istio-system
  chartRef:
    kind: OCIRepository
    name: istiod
    namespace: flux-system
  interval: 5m
  releaseName: istiod
  dependsOn:
    - name: istio-base
  values:
    meshConfig:
      accessLogFile: "/dev/stdout"
    pilot:
      autoscaleEnabled: true
