apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istio-base
  namespace: istio-system
spec:
  install:
    createNamespace: true
  targetNamespace: istio-system
  chartRef:
    kind: OCIRepository
    name: istiod
    namespace: flux-system
  interval: 5m
  releaseName: base
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istiod
  namespace: istio-system
spec:
  install:
    createNamespace: true
  targetNamespace: istio-system
  chartRef:
    kind: OCIRepository
    name: istiod
    namespace: flux-system
  interval: 5m
  releaseName: istiod
  dependsOn:
    - name: istio-base
  values:
    meshConfig:
      accessLogFile: "/dev/stdout"
    pilot:
      autoscaleEnabled: true
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istio-ingressgateway
  namespace: istio-system
spec:
  releaseName: istio-ingressgateway
  targetNamespace: istio-system
  interval: 5m
  chartRef:
    kind: OCIRepository
    name: gateway
    namespace: flux-system
  dependsOn:
    - name: istiod
  values:
    gateways:
      istio-ingressgateway:
        enabled: true
        type: LoadBalancer
        ports:
          - name: http
            port: 80
            targetPort: 8080
          - name: https
            port: 443
            targetPort: 8443
