apiVersion: batch/v1
kind: CronJob
metadata:
  name: ecr-secret-refresh
  namespace: flux-system
spec:
  schedule: "0 */6 * * *"  # Every 10 minutes
  jobTemplate:
    spec:
      template:
        spec:
          securityContext:
            seccompProfile:
              type: RuntimeDefault
          serviceAccountName: ecr-secret-updater
          containers:
            - name: updater
              image: amazonlinux:2023
              command:
                - /bin/sh
                - -c
                - |
                  set -e
                  yum install -y aws-cli jq
                  export AWS_ACCESS_KEY_ID=$(aws ssm get-parameter --name /kraken/gardener/ecr/key_id --with-decryption --query 'Parameter.Value' --output text)
                  export AWS_SECRET_ACCESS_KEY=$(aws ssm get-parameter --name /kraken/gardener/ecr/access_key --with-decryption --query 'Parameter.Value' --output text)
                  export AWS_DEFAULT_REGION=us-west-2
                  kubectl create secret docker-registry ce-ecr-auth \
                    --namespace flux-system \
                    --docker-server=043309336908.dkr.ecr.us-west-2.amazonaws.com \
                    --docker-username=AWS \
                    --docker-password="$(aws ecr get-login-password --region us-west-2)" \
                    --dry-run=client -o yaml | kubectl apply -f -
              env:
                - name: AWS_REGION
                  value: us-west-2
              securityContext:
                allowPrivilegeEscalation: false
                runAsNonRoot: true
                capabilities:
                  drop:
                    - ALL
          restartPolicy: OnFailure