apiVersion: apps/v1
kind: Deployment
metadata:
  name: helm-controller
spec:
  template:
    spec:
      containers:
        - name: manager
          image: 043309336908.dkr.ecr.us-west-2.amazonaws.com/ce-addon-images/fluxcd-helm-controller:v1.3.0
