apiVersion: apps/v1
kind: Deployment
metadata:
  name: keda
spec:
  template:
    spec:
      containers:
        - name: manager
          image: 043309336908.dkr.ecr.us-west-1.amazonaws.com/ce-addon-images/kedacore-keda:2.14.0
