apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-reflector
spec:
  template:
    spec:
      containers:
        - name: manager
          image: 043309336908.dkr.ecr.us-west-2.amazonaws.com/ce-addon-images/emberstack-kubernetes-reflector:9.1.7
