apiVersion: apps/v1
kind: Deployment
metadata:
  name: kustomize-controller
spec:
  template:
    spec:
      containers:
        - name: manager
          image: 043309336908.dkr.ecr.us-west-1.amazonaws.com/ce-addon-images/fluxcd-kustomize-controller:v1.6.0
