---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: gatekeeper
  namespace: flux-system
spec:
  url: https://open-policy-agent.github.io/gatekeeper/charts
  interval: 10m
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gatekeeper
  namespace: gatekeeper-system
spec:
  install:
    createNamespace: true
  targetNamespace: gatekeeper-system
  chart:
    spec:
      chart: gatekeeper
      version: "3.14.0"
      sourceRef:
        kind: HelmRepository
        name: gatekeeper
        namespace: flux-system
  interval: 5m